configuration_path: '/home/tkztmk/.kaunas.conf.json'
default_site_title: 'sera nimis uita est crastina: uiue hodie!' 
default_site_contact: 'mailto: tkztmk@outlook.com'
default_site_author: 'Takezoe Tomoaki'


